pdf_urls = {
  "Expert Tips on How to Stop Puppy Mouthing and Nipping": "https://www.akc.org/expert-advice/training/puppy-mouthing-expert-tips/",
  "How To Stop a Puppy From Biting PetMD": "https://www.petmd.com/dog/training/puppy-biting",
  "How to Stop Puppy Biting and Train Bite Inhibition American Kennel Club": "https://www.akc.org/expert-advice/training/stop-puppy-biting/",
  "How to Stop Puppy Biting Purina": "https://www.purina.com/articles/dog/puppy/behavior/how-to-stop-puppy-biting",
  "Mouthing, Nipping and Biting in Puppies ASPCA": "https://www.aspca.org/pet-care/dog-care/common-dog-behavior-issues/mouthing-nipping-and-biting-puppies#:~:text=Either%20ignore%20him%20for%2010,continues%2C%20but%20painful%20play%20stops.",
  "Play Biting in Puppies VCA Animal Hospital VCA Animal Hospitals": "https://vcahospitals.com/know-your-pet/play-biting-in-puppies#:~:text=If%20your%20puppy%20begins%20to,as%20soon%20as%20biting%20begins.",
  "Crate training your dog or puppy Animal Humane Society": "https://www.animalhumanesociety.org/resource/crate-training-your-dog-or-puppy#:~:text=Drop%20some%20treats%20around%20the,crate%20to%20get%20a%20treat.",
  "How Long Can a Dog Stay in a Crate Impact Dog Crates": "https://www.impactdogcrates.com/blogs/puppy-news/how-long-can-a-dog-stay-in-a-crate?pb=0",
  "How Long Is Too Long To Crate Your Dog": "https://petprosupplyco.com/blogs/blog/how-long-is-too-long-to-crate-your-dog",
  "How to crate train a dog or puppy The Humane Society of the United States": "https://www.humanesociety.org/resources/crate-training-101",
  "How to Crate Train Your Dog in Nine Easy Steps American Kennel Club": "https://www.akc.org/expert-advice/training/how-to-crate-train-your-dog-in-9-easy-steps/",
  "What is the maxmimum hours in... Rover Q&A Community": "https://www.rover.com/community/question/42029/what-is-the-maximum-stay-for-doggy-day-care/",
  "26 Tricks To Stop Your Dog From Digging Up Your Yard - Dog Lab": "https://doglab.com/stop-dog-digging/",
  "5 Ways To Stop Your Dog From Digging Holes In The Yard": "https://doggoneamazing.com/5-surefire-ways-to-stop-your-dog-from-digging-holes-in-the-yard/",
  "How to get your dog to stop digging The Humane Society of the United States": "https://www.humanesociety.org/resources/stop-dogs-digging#:~:text=Provide%20your%20dog%20with%20the,setting%20aside%20a%20digging%20zone.",
  "How to Stop a Dog from Digging Holes, Under the Fence & More": "https://www.rover.com/blog/how-to-stop-dog-digging/",
  "Why Does My Dog Dig Identify And Channel Your Dog's Digging Instincts": "https://www.akc.org/expert-advice/advice/why-is-my-dog-digging/",
  "5 Critical Stages of Development — CreamofBritish": "https://aldlabradoodles.uk/5-stages-of-development",
  "Critical Period in the Social Development of Dogs - science.133.3457.1016": "https://pubmed.ncbi.nlm.nih.gov/13701603/",
  "Critical Periods in Your Pup's Growth Doglistener": "https://www.doglistener.co.uk/criticalperiods-shtml",
  "Important Times - Critical Periods of Development All Dogs Gym": "https://www.alldogsgym.com/important-times-critical-periods-of-development/",
  "Expert Tips on How to Stop a Dog From Jumping Up": "https://www.akc.org/expert-advice/training/stop-dog-jumping/#:~:text=If%20your%20dog%20jumps%20on,quietly%20praise%20and%20pet%20them.",
  "How to Stop a Dog from Jumping Up in 5 Easy Steps Zoom Room Dog Training": "https://zoomroom.com/admin/stop-dog-jumping/",
  "How to stop your dog from jumping The Humane Society of the United States": "https://www.humanesociety.org/resources/how-stop-your-dog-jumping#:~:text=Teach%20your%20dog%20that%20they,up%20at%20the%20same%20time.",
  "How to Stop Your Dog From Jumping Up on People": "https://www.akc.org/expert-advice/training/how-to-stop-your-dog-from-jumping-up-on-people/",
  "How to Train a Dog Not to Jump on You or Others The Dog People CA": "https://www.rover.com/ca/blog/train-dog-not-jump-others/",
  "Reasons Why Your Dog Jumps Up and How to Stop It": "https://www.thesprucepets.com/how-to-stop-jumping-in-dogs-1117873",
  "How to Leash Train a Dog A Step-by Step Guide BeChewy": "https://be.chewy.com/leash-train-dog-2/",
  "How to Leash Train a Dog MeatEater Hunting": "https://www.themeateater.com/hunt/dog/how-to-leash-train-a-dog",
  "How to Stop Pulling on Leash - FernDog Training": "https://ferndogtraining.com/pulling-on-leash/",
  "How To Teach Your Dog To Walk On A Leash… - Brandon McMillan's Canine Minded": "https://canineminded.com/train-dog-walk-on-leash/",
  "Leash Training How to Train a Dog or Puppy to Walk on a Leash": "https://www.akc.org/expert-advice/training/teach-puppy-walk-leash/",
  "Teach your dog to walk on a loose leash Animal Humane Society": "https://www.animalhumanesociety.org/resource/teach-your-dog-walk-loose-leash",
  "My Dog Ate a Sock, Is It Dangerous What to Do Next Dogster": "https://www.dogster.com/dog-health-care/dog-ate-a-sock-what-to-do",
  "Pica in Dogs Why Your Dog Eats Rocks, Dirt, and Clothes": "https://petcube.com/blog/pica-in-dogs/",
  "What Is Pica In Dogs Causes, Symptoms, & Treatment - GoodRx": "https://www.goodrx.com/pet-health/dog/pica-in-dogs-causes",
  "Why Does My Dog Chew on My Underwear and Socks": "https://www.akc.org/expert-advice/training/why-does-my-dog-chew-on-my-underwear-and-socks/",
  "Why Does My Dog Eat My Socks": "https://www.thesprucepets.com/why-does-my-dog-eats-socks-3385603",
  "Why Does My Dog Eat My Underwear": "https://www.thesprucepets.com/why-your-dog-eats-your-underwear-5204193",
  "Why Does My Dog Eat My Underwear KONG Club": "https://kongclub.app/why-does-my-dog-eat-my-underwear/#:~:text=When%20it%20comes%20to%20your,perfume%20to%20our%20furry%20pals.",
  "Why Dogs Eat Underwear And Socks": "https://www.rover.com/blog/why-dog-eat-underwear/#:~:text=Since%20underwear%20and%20socks%20are,skivvies%20as%20a%20chew%20toy.",
  "How to Potty Train A Dog in 7 Days BeChewy": "https://be.chewy.com/how-to-potty-train-your-dog-in-7-days/#:~:text=Take%20your%20puppy%20to%20a,puppy%20pees%20or%20poops%20outside.",
  "How to Potty Train a Dog Potty Training Tips for Puppies and Adult Dogs PetMD": "https://www.petmd.com/dog/general-health/how-to-potty-train-a-puppy",
  "Potty Training a Puppy How to House Train Puppies": "https://www.akc.org/expert-advice/training/how-to-potty-train-a-puppy/",
  "Puppy Potty Training Tips from Expert Dog Trainers": "https://www.akc.org/expert-advice/training/potty-training-puppy-tips/#:~:text=Give%20Your%20Puppy%20a%20Routine&text=That%20doesn%27t%20just%20mean,makes%20potty%20urges%20happen%2C%20too.",
  "Tips on how to potty train your dog or puppy The Humane Society of the United States": "https://www.humanesociety.org/resources/how-potty-train-your-dog-or-puppy",
  "Canine separation anxiety strategies for treatment and management - PMC": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7521022/",
  "How to Help a Dog With Separation Anxiety PetMD": "https://www.petmd.com/dog/training/how-help-dog-separation-anxiety",
  "Separation Anxiety ASPCA": "https://www.aspca.org/pet-care/dog-care/common-dog-behavior-issues/separation-anxiety",
  "Separation Anxiety How to Keep Your Dog Calm When You Leave": "https://www.webmd.com/pets/dogs-separation-anxiety",
  "Separation Anxiety in Dogs Signs, Causes, and Prevention": "https://www.akc.org/expert-advice/training/dog-separation-anxiety/",
  "Separation Anxiety in Dogs VCA Animal Hospital VCA Animal Hospitals": "https://vcahospitals.com/know-your-pet/separation-anxiety-in-dogs#:~:text=Dogs%20with%20separation%20anxiety%20vocalize,often%20occurs%20shortly%20after%20departure.",
  "How to Help A Dog That’s Missed Early Socialization": "https://www.preventivevet.com/dogs/how-to-help-adult-dog-with-socialization",
  "How to Introduce a New Dog to Your Current Dog American Kennel Club": "https://www.akc.org/expert-advice/training/how-to-introduce-dogs/",
  "How to Introduce a New Dog to Your Current Dog CESAR": "https://www.cesar.com/dog-care/socialization/how-to-introduce-a-new-dog-to-your-current-dog",
  "How to Introduce Your New Puppy to Your Dog! — The Puppy Academy": "https://www.thepuppyacademy.com/blog/2022/3/28/how-to-introduce-your-new-puppy-to-your-dog",
  "How to Safely Introduce Your New Puppy to Your Dog — Pumpkin": "https://www.pumpkin.care/blog/how-to-introduce-puppy-to-dog/",
  "How to Socialize an Adult Dog and Why It’s Never Too Late": "https://www.houndslounge.com/blog/how-to-socialize-an-adult-dog-and-why-its-never-too-late/",
  "How to Successfully Socialize a Puppy": "https://www.webmd.com/pets/dogs/socializing-new-puppy",
  "Introducing a New Dog to Your Current Dog Indoor Pet Initiative": "https://indoorpet.osu.edu/dogs/new_additions_dogs/dog-dog-intro#:~:text=Try%20to%20introduce%20the%20new,comfortable%20in%20his%20new%20home.",
  "Introducing A New Puppy or Dog to Your Dog Dogs Trust": "https://www.dogstrust.org.uk/dog-advice/life-with-your-dog/at-home/introducing-new-puppy",
  "Puppy Socialization How to Socialize a Puppy": "https://www.akc.org/expert-advice/training/puppy-socialization/#:~:text=Introduce%20the%20puppy%20to%20new%20sights%2C%20sounds%2C%20and%20smells&text=Try%20to%20come%20up%20with,expose%20your%20puppy%20to%20them.",
  "Socializing your dog Animal Humane Society": "https://www.animalhumanesociety.org/resource/socializing-your-dog#:~:text=If%20your%20heart%20is%20set,get%20accustomed%20to%20each%20other.",
  "Socializing Your Pup 8 Tips for Helping Them Mingle with Dogs & Humans": "https://www.rover.com/blog/how-to-socialize-dog/",
  "Tips for Socializing a Puppy ASPCApro": "https://www.aspcapro.org/resource/tips-socializing-puppy#:~:text=The%20most%20critical%20aspect%20of,playdates%20to%20socialize%20your%20puppy.",
  "13 Best & Safe Chew Toys For Puppies (To Keep Them Busy)": "https://www.thesprucepets.com/best-chew-toys-for-puppies-4173915",
  "How to Identify a Dangerous Dog Toy, According to Experts": "https://www.rover.com/blog/toxic-pet-toys-beds-safety-guide/",
  "Protect Your Pup Avoid These Dangerous Dog Toys Dutch": "https://www.dutch.com/blogs/dogs/dangerous-dog-toys#:~:text=Toys%20with%20strings%2C%20such%20as,thin%20pieces%20of%20long%20string.",
  "The Best Chew Toys for a Teething Puppy Kahoots": "https://kahootsfeedandpet.com/blogs/blog/the-best-chew-toys-for-a-teething-puppy",
  "The dangers of cheap and chewable dog toys - Pooches At Play": "https://poochesatplay.com/toys-accessories/dangers-cheap-chewable-dog-toys/",
  "Top 4 Most Dangerous Dog Toys River Road Veterinary Clinic": "https://riverroadveterinary.com/top-4-most-dangerous-dog-toys/",
  "Top Dog Toys for Teething Puppies Cave Creek Vet": "https://www.cahosp.com/post/top-dog-toys-for-teething-puppies",
  "13 best dog treats in 2024, according to pet experts": "https://www.nbcnews.com/select/shopping/best-dog-treats-ncna1234429",
  "Best Dog Treats 2024 DogFoodAdvisor": "https://www.dogfoodadvisor.com/best-dog-foods/best-dog-treats/",
  "Best Dog Treats How to Choose the Best Treats for Training": "https://www.akc.org/expert-advice/training/best-dog-treats-choose-right-treats-dog/",
  "Is Rawhide Bad for Dogs Is Rawhide Bad for Puppies Petco": "https://www.petco.com/content/petco/PetcoStore/en_US/pet-services/resource-center/food-nutrition/is-rawhide-bad-for-dogs.html",
  "Rawhide Bones and Treats for Dogs Risks and Benefits": "https://www.webmd.com/pets/dogs/rawhide-good-or-bad-for-your-dog",
  "The 10 Best Dog Treats To Get Tails Wagging - Forbes Vetted": "https://www.forbes.com/sites/forbes-personal-shopper/article/best-dog-treats/?sh=1b750c8e325f",
  "The Raw Truth About Rawhide Is Rawhide Bad for Dogs Tartar Shield": "https://www.tartarshield.com/blogs/health/the-raw-truth-about-rawhide-is-rawhide-bad-for-dogs",
  "Best Dog Food Brands Vets Buy for Their Own Pets": "https://www.rd.com/list/dog-food-brands-vets-buy/",
  "Can My Dog Eat This A List of Human Foods Dogs Can and Can't Eat": "https://www.healthline.com/nutrition/human-foods-for-dogs",
  "Dog Feeding Time How Much and How Often ": "https://www.webmd.com/pets/dogs/feeding-time",
  "Dogs and Raw Food Diets VCA Animal Hospital VCA Animal Hospitals": "https://vcahospitals.com/know-your-pet/dogs-and-raw-food-diets",
  "Feeding Times and Frequency for Your Dog VCA Animal Hospital VCA Animal Hospitals": "https://vcahospitals.com/know-your-pet/feeding-times-and-frequency-for-your-dog#:~:text=Dogs%20should%20eat%20at%20least,can%20become%20hyperacidic%20causing%20nausea.",
  "Homemade Dog Food Recipes Choosing Balanced Ingredients": "https://www.akc.org/expert-advice/nutrition/choosing-ingredients-homemade-dog-food/",
  "How Often Should Dogs Eat and How Much Should You Feed Them ": "https://www.akc.org/expert-advice/nutrition/how-often-should-dogs-eat/#:~:text=Diet%20and%20nutrition%20are%20crucial,frequency%20is%20meal%20portion%20size.",
  "How We Rate Dog Food Frequently Asked Questions": "https://www.dogfoodadvisor.com/frequently-asked-questions/rate-dog-food/#:~:text=How%20do%20you%20determine%20the,or%20plant%2Dbased%20protein%20boosters.",
  "Human Foods Dogs Can Eat Complete List BetterVet": "https://bettervet.com/resources/pet-nutrition/human-food-dogs-can-eat",
  "Human foods for dogs Which foods are safe for dogs ": "https://www.medicalnewstoday.com/articles/324453",
  "One veterinarian’s experience with owners who are feeding raw meat to their pets - PMC": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6515799/",
  "People Food Dogs Can Eat and Can’t Eat American Kennel Club": "https://www.akc.org/expert-advice/nutrition/human-foods-dogs-can-and-cant-eat/",
  "Raw Dog Food Diet Benefits and Risks": "https://www.webmd.com/pets/dogs/features/raw-dog-food-dietary-concerns-benefits-and-risks",
  "The best dog food in March 2024, according to experts": "https://www.nbcnews.com/select/shopping/best-dog-food-ncna1189551",
  "The Best Dry Dog Food Brands 2024 DogFoodAdvisor": "https://www.dogfoodadvisor.com/best-dog-foods/best-dry-dog-foods/",
  "The truth about taurine and dog food DogFoodAdvisor": "https://www.dogfoodadvisor.com/canine-nutrition/taurine-and-dog-food/#:~:text=So%20how%20important%20is%20taurine,on%20meats%20and%20other%20proteins.",
  "Top 10 Healthiest Human Foods That Dogs Can Eat": "https://www.splootvets.com/post/healthiest-human-foods-dogs-can-eat",
  "Vet-Approved Homemade Dog Food Recipes": "https://www.thesprucepets.com/homemade-dog-food-recipes-5200240",
  "What’s the Ideal Feeding Schedule for Dogs - Whole Dog Journal": "https://www.whole-dog-journal.com/food/whats-the-ideal-feeding-schedule-for-dogs/",
  "What's the best dog food Experts recommend these four.": "https://www.usatoday.com/story/life/2023/08/10/what-is-the-best-dog-food/70428212007/",
  "When & How Often Should Dogs Be Fed Cedar Mill Veterinary Hospital Portland Vets": "https://www.cedarmillvet.com/site/blog/2022/05/31/feeding-your-dog#:~:text=Your%20Dog%27s%20Digestion&text=This%20timing%20of%20the%20hunger,least%202%20meals%20per%20day.",
  "Canine parvovirus American Veterinary Medical Association": "https://www.avma.org/resources-tools/pet-owners/petcare/canine-parvovirus",
  "Canine Parvovirus Cornell University College of Veterinary Medicine": "https://www.vet.cornell.edu/departments-centers-and-institutes/baker-institute/our-research/canine-parvovirus",
  "Canine Parvovirus Symptoms and Treatment Blue Cross": "https://www.bluecross.org.uk/advice/dog/health-and-injuries/parvovirus-in-dogs#:~:text=The%20virus%20attacks%20cells%20in,vaccinating%20your%20dog%20is%20vital.",
  "Parvo In Dogs Forbes Advisor": "https://www.forbes.com/advisor/pet-insurance/pet-care/parvo-in-dogs/",
  "Parvovirus Dangers, Risks, and How to Protect Your Puppy": "https://www.webmd.com/pets/dogs/what-is-parvovirus",
  "What Every Puppy Owner Needs to Know About Parvo in Puppies": "https://www.akc.org/expert-advice/health/what-every-puppy-owner-needs-to-know-about-parvo-in-puppies/",
  "What is Parvo in Dogs Purina": "https://www.purina.com/articles/dog/puppy/health/what-is-parvo#:~:text=Canine%20parvovirus%20is%20a%20viral,intestinal%20lining%20and%20bone%20marrow.",
  "4": "https://www.petmd.com/dog/care/dog-vaccinations-for-every-lifestage",
  "A Guide To Vaccination For Your Dog - Tampa Bay Animal Hospital Group": "https://www.tampabayvets.net/guide-vaccination-dog/#:~:text=Vaccination%20Programs%20For%20Your%20Dog,of%20exposure%20to%20infectious%20disease.",
  "Adult Dog and Puppy Vaccinations - Westbay Animal Hospital": "https://westbayanimalhospital.com/adult-dog-and-puppy-vaccinations/",
  "Care for Your Pet After Vaccination VCA Animal Hospital VCA Animal Hospitals": "https://vcahospitals.com/know-your-pet/care-for-your-pet-after-vaccination",
  "Dog Vaccinations - Everything you must know": "https://www.4pawsanimal.com/services/dogs/dog-vaccinations",
  "How to Handle a Vaccine Reaction in Your Dog Greensboro Vet Guilford-Jamestown Veterinary Hospital": "https://www.guilfordjamestownvet.com/site/blog-greensboro-vet/2021/01/28/vaccine-reaction-dog",
  "Puppies Going Outside Timeline, Vaccinations, and Indoor Play": "https://www.rover.com/blog/when-can-puppies-go-outside/",
  "Puppy Shots Schedule A Complete Guide to Puppy Vaccinations": "https://www.akc.org/expert-advice/health/puppy-shots-complete-guide/",
  "Puppy Vaccinations When to Get Them and Why PetSmart": "https://www.petsmart.com/learning-center/dog-care/puppy-vaccinations-when-to-get-them-and-why/A0067.html#:~:text=A%20typical%20puppy%20vaccination%20schedule%20is%20their%20first%20vaccination%20at,16%2D20%20weeks%20for%20DHP.",
  "Vaccinations American Veterinary Medical Association": "https://www.avma.org/resources-tools/pet-owners/petcare/vaccinations",
  "Vaccine Reactions in Dogs - What Pet Parents Should Know Windsor Vets": "https://www.nevccc.com/site/blog/2022/08/30/vaccination-reactions-dog",
  "Vaccine Reactions in Dogs What You Need to Know": "https://www.littlemiamivetclinic.com/site/blog/2022/02/28/vaccine-reactions-dogs-everything-you-should-know",
  "Vaccines for Dogs VCA Animal Hospital VCA Canada Animal Hospitals": "https://vcahospitals.com/know-your-pet/vaccines-for-dogs#:~:text=The%20range%20of%20vaccines%20available,%E2%80%9CDistemper%20in%20Dogs%E2%80%9D%2C%20%E2%80%9C",
  "What to Do If Your Dog Has a Reaction to a Vaccine North Asheville Vet Annual Vaccines for Pets": "https://www.ahna.net/site/blog-asheville-vet/2021/01/18/what-to-do-reaction-vaccine-dog",
  "What To Know About Possible Vaccine Reactions in Dogs PetMD": "https://www.petmd.com/dog/general-health/possible-vaccine-reactions-in-dogs",
  "When Can A Puppy Go Outside ": "https://scrumbles.co.uk/blogs/dog/when-can-puppies-go-outside?_pos=1&_sid=39c6eab41&_ss=r",
  "When Can a Puppy Go Outside Safely PetMD": "https://www.petmd.com/dog/general-health/when-can-puppy-go-outside",
  "When Can My Puppy Go Outside - Lakeland Animal Clinic": "https://lacvets.com/blog/when-can-my-puppy-go-outside/#:~:text=It%20is%20considered%20safe%20for,usually%20at%2016%20weeks%20old.",
  "When Can Puppies Go Outside All You Need to Know Purina": "https://www.purina.co.uk/articles/dogs/puppy/welcoming/when-can-puppies-go-outside#:~:text=Generally%2C%20puppies%20can%20go%20outside,they%27ve%20been%20vaccinated%20against.",
  "6 Winter Safety Tips for Dogs in Snow Purina": "https://www.purina.com/articles/dog/health/routine-care/how-to-protect-dogs-in-cold-snow-ice",
  "9 Hot Tips for Taking Your Dog to the Beach": "https://www.rover.com/blog/9-hot-tips-taking-dog-beach/",
  "Caring for your Dogs in Snow & Cold Temperatures Medivet": "https://www.medivetgroup.com/pet-care/pet-advice/dog-freezing-temperatures-snow/#:~:text=Ideally%2C%20your%20dog%27s%20coat%20should,night%20that%27s%20a%20real%20benefit.",
  "Dog Snow Safety 101 Zoetis Petcare": "https://www.zoetispetcare.com/blog/article/dog-snow-safety-101#:~:text=Depending%20on%20the%20thickness%20of,underneath%20a%20waterproof%20dog%20coat.",
  "Keep Your Dog Safe at the Beach Dog Swimming Tips Kirrawee": "https://www.kirraweevet.com.au/pet-care/pet-care-for-dogs/5-tips-to-keep-your-dog-safe-on-the-beach.html",
  "Snow Dog Breeds 20 Best Pups for Winter Adventures - Outside Online": "https://www.outsideonline.com/outdoor-adventure/snow-sports/20-best-cold-weather-dog-breeds/",
  "Taking Your Dog to the Beach Tips & Safety": "https://www.akc.org/expert-advice/travel/tips-for-taking-dog-to-beach/",
  "The 32 Best Dog-Friendly Beaches in the U.S.": "https://travel.usnews.com/gallery/the-best-dog-friendly-beaches-in-the-us",
  "Dog_Pawsitivity_Final - Dog_Pawsitivity_Final-min-1": "https://www.rover.com/blog/wp-content/uploads/2019/04/Dog_Pawsitivity_Final-min-1.pdf",
  "How Much Exercise Do Dogs Need - The Farmer's Dog": "https://www.thefarmersdog.com/digest/how-much-exercise-do-dogs-need/#:~:text=The%20longer%20answer%3A%20Ideally%20longer,to%20get%20out%20for%20walks.",
  "How Much Exercise Does a Dog Need Every Day ": "https://www.akc.org/expert-advice/health/how-much-exercise-does-dog-need/",
  "How Much Exercise Does a Dog Need Purina": "https://www.purina.com/articles/dog/behavior/play/how-much-exercise-does-a-dog-need#:~:text=Generally%2C%20most%20breeds%20need%20more,how%20much%20exercise%20is%20best.",
  "Signs a Dog May Need More Exercise - Outdoor Dog Adventures Professional Dog Walking Louisville, KY": "https://outdoordogadventures.com/2018/03/11/signs-a-dog-may-need-more-exercise/",
  "[Product Comparison Chart] The Best Flea Tick & Heartworm Meds PetMeds®": "https://www.1800petmeds.com/education/heartworm-flea-combo-medicine-8.html",
  "6 Best Tick Treatments for Dogs The Strategist": "https://nymag.com/strategist/article/best-tick-treatment-for-dogs.html",
  "Back To Basics Flea, Tick, and Heartworm Prevention Bowman Veterinary Hospital": "https://www.bowmanvet.com/blog/back-to-basics-flea-tick-and-heartworm-prevention/",
  "Best flea and tick medicines for dogs reviews": "https://www.sltrib.com/sponsored/2022/10/05/best-flea-tick-medicines-dogs/",
  "Do Dogs Need Flea and Tick Medicine in the Winter Small Door Veterinary": "https://www.smalldoorvet.com/learning-center/wellness/flea-tick-after-summer",
  "Flea and Tick Prevention": "https://www.aspcapetinsurance.com/resources/flea-and-tick-prevention/",
  "Flea, Tick & Heartworm Prevention for Puppies - Free shipping Chewy": "https://www.chewy.com/b/puppy-flea-tick-2807",
  "Guide to Flea and Tick Prevention for Dogs PetMD": "https://www.petmd.com/dog/general-health/flea-and-tick-prevention-and-treatment-dogs",
  "Heartworm, Flea, and Tick Prevention": "https://www.apcnv.com/articles/flea-prevention-and-care.html#:~:text=Preventive%20care%20is%20so%20important,trouble%20for%20cats%20and%20dogs.",
  "How Long Do Flea and Tick Medications Take to Work on Dogs PetMD": "https://www.petmd.com/dog/general-health/how-long-do-flea-and-tick-medications-take-work-dogs",
  "How Often Should I Give My Dog a Flea and Tick Treatment Hartz": "https://www.hartz.com/often-give-dog-flea-tick-treatment/#:~:text=Flea%20drops%3A%20Hartz%20flea%20drops,against%20reinfestation%20for%20two%20weeks.",
  "How Often Should I Treat My Dog for Fleas ": "https://www.k9magazine.com/how-often-should-i-treat-my-dog-for-fleas/#:~:text=Experts%20say%20treating%20dogs%20for,and%20will%20make%20him%20itchy.",
  "How to Choose the Best All-in-One Heartworm and Flea Pill for Dogs PetMD": "https://www.petmd.com/dog/parasites/how-choose-best-all-one-heartworm-and-flea-pill-dogs",
  "The 6 Best Flea and Tick Treatments for Dogs in 2024": "https://www.businessinsider.com/guides/pets/best-flea-treatment-dogs",
  "The Best Heartworm, Flea, Ticks, and Parasite Prevention Medicines for Dogs PetCareRx": "https://www.petcarerx.com/article/the-best-heartworm-flea-ticks-and-parasite-prevention-medicines-for-dogs/6203",
  "Top 4 All in One Treatments for Fleas, Ticks and Heartworms in 2023": "https://www.canadapetcare.com/blog/all-in-one-fleas-ticks-and-heartworm-treatments/",
  "What is Your State's Flea and Tick Season ": "https://www.akc.org/expert-advice/health/flea-tick-season/",
  "Dog Nail Trimming How to Cut Dog Nails the Safe and Stress-Free Way PetMD": "https://www.petmd.com/dog/grooming/evr_dg_how_to_trim_a_dogs_toenails",
  "How Often Should I Trim My Dog's Nails The Dog People by Rover.com": "https://www.rover.com/blog/how-often-should-i-trim-my-dogs-nails/",
  "How Often Should You Cut Your Dog's Nails Preventive Vet": "https://www.preventivevet.com/dogs/how-often-should-you-cut-your-dogs-nails#:~:text=A%20good%20rule%20of%20thumb,the%20top%20of%20this%20article).",
  "How to Cut Dog Nails Tips from a Groomer BeChewy": "https://be.chewy.com/guide-trimming-dogs-nails/#:~:text=Always%20make%20sure%20you%20have,middle%20of%20the%20nail%20tip.",
  "How to Trim a Dog's Nails VCA Animal Hospitals": "https://vcahospitals.com/know-your-pet/how-to-trim-a-dogs-nails#:~:text=If%20your%20dog%20has%20light,tip%20off%20of%20the%20nail.",
  "Importance of Trimming Your Pet’s Nails": "https://advancedpetvet.com/2021/02/02/why-is-it-important-to-trim-your-pets-nails/",
  "Trim Your Dog's Nails Safely Tips, Tricks, And Grooming Techniques": "https://www.akc.org/expert-advice/health/how-to-trim-dogs-nails-safely/",
  "Is Pet Insurance Worth It 2024 Guide - NerdWallet": "https://www.nerdwallet.com/article/insurance/is-pet-insurance-worth-it",
  "Is pet insurance worth it Here's what vets say - CBS News": "https://www.cbsnews.com/news/is-pet-insurance-worth-it-heres-what-vets-say/",
  "Is Pet Insurance Worth It In 2024 Forbes Advisor": "https://www.forbes.com/advisor/pet-insurance/is-pet-insurance-worth-it/",
  "Is Pet Insurance Worth It In 2024 Here’s A Vet’s Perspective Pawlicy Advisor": "https://www.pawlicy.com/blog/is-pet-insurance-worth-it/",
  "Is Pet Insurance Worth It U.S. News": "https://www.usnews.com/insurance/pet-insurance/is-pet-insurance-worth-it",
  "Emotional Support Animal Registration What to Know": "https://usaservicedogregistration.com/registration/",
  "How to Get a Legitimate Emotional Support Animal (or ESA Letter)": "https://www.certapet.com/emotional-support-animal/",
  "How to Register an Emotional Support Animal - ESA Doctors": "https://esadoctors.com/register-dog-emotional-support-animal/",
  "Your Complete Guide To ESA & Service Animal Registration": "https://usserviceanimals.org/support/faq" 
}